### PR TITLE
Setup license header for VS Code users

### PR DESCRIPTION
**Pull request by deekim**
leveraging the [ymotongpoo/vsc-licenser](https://github.com/ymotongpoo/vsc-licenser) extension.

I wasn't sure if we wanted this to be committed since it is `IDE` specific,
but I thought that I would at least open up the discussion.

### CODE REVIEW

**Comment by msargentibm** [comment]
Is this something you are using and sharing just in case others are interested?

**Comment by deekim** [comment]
> Is this something you are using and sharing just in case others are interested?

It is what VS Code considers a ["workspace settings override"](https://code.visualstudio.com/docs/getstarted/settings)
> Workspace settings override user settings. 
> Workspace settings are specific to a project and can be shared across developers on a project.

**Review by csandersdev — APPROVED** [review]
Doesn't seem like it would interfere with another IDE, so I don't have a problem with it.

**Comment by msargentibm** [comment]
>Doesn't seem like it would interfere with another IDE, so I don't have a problem with it.

Ditto. Were there any specific issues you were hoping to discuss @deekim ?

**Comment by deekim** [comment]
> > Doesn't seem like it would interfere with another IDE, so I don't have a problem with it.
> 
> Ditto. Were there any specific issues you were hoping to discuss @deekim ?

Nope :)

**Pull request merged**
