### PR TITLE
add intial performance metrics for measure engine

### PR DESCRIPTION
**Pull request by deekim**
_addresses_ [WFFHCOHORT-30](https://jsw.ibm.com/browse/WFFHCOHORT-30)

---

rendered preview: [deekim/quality-measure-and-cohort-service](https://deekim.github.io/quality-measure-and-cohort-service/#/dev-guide/spikes/initial-performance-evaluation)

### CODE REVIEW

**Review by msargentibm — APPROVED** [review]
Looks good. Are these numbers all for single runs of `#measure/#patient` combinations?

**Review by csandersdev — CHANGES_REQUESTED** [review]
This is a good start. That said, there are a number of things that I would typically report when I do a performance evaluation. Specifically, I would want to document the FHIR server scaling parameters (how many nodes, amount of JVM memory, anything else?) and the DB setup (DB2 plan type, number of CPUs, amount of RAM, etc.).

For FHIR...
1 K8s pod with 4CPU, 16 GB RAM, 4GB Java heap

For DB2...
image

**Comment by deekim** [comment]
> Looks good. Are these numbers all for single runs of `#measure/#patient` combinations?
@msargentibm yes.

> This is a good start. That said, there are a number of things that I would typically report when I do a performance evaluation. Specifically, I would want to document the FHIR server scaling parameters (how many nodes, amount of JVM memory, anything else?) and the DB setup (DB2 plan type, number of CPUs, amount of RAM, etc.).
> 
> For FHIR...
> 1 K8s pod with 4CPU, 16 GB RAM, 4GB Java heap

@CoreySandersOH I agree with you those are important things. Those weren't really outlined in the initial ticket.
We can talk more during standup, but maybe what you are talking about should be part of a separate ticket when we have set up a more automated way to test performance?

**Comment by deekim** [comment]
It wasn't exactly clear if you wanted me to test tuning the `FHIR` and `DB2` to achieve better performance,
but minimally, I added that information to the docs (a604eae)

**Review by jillrdoty — APPROVED** [review]
Looks good, I'm happy with just documenting the DB2 / FHIR specs, I don't expect to try to tune those as part of this.

**Comment by csandersdev** [comment]
@deekim Just add the documentation. I wasn't looking for you to tune and retest. Having the scale documented is just an important part of understanding the baseline. We kind of have it as institutional knowledge on our team right now, but as we move into performance tuning in future sprints it will be good to have the knowledge documented.

**Review by csandersdev — APPROVED** [review]

**Pull request merged**
