### PR TITLE
Sonar spark

### PR DESCRIPTION
**Pull request by jillrdoty**
Adding a github workflow for sonar to run on the spark branch.

### CODE REVIEW

**Review by csandersdev — COMMENTED** [review]
I've been waiting to see this pass checks to approve. Do we know what needs to be done to make it pass?

**Comment by jaigoradia** [comment]
It is failing on the container-vulnerability-check step of CI pipeline.  One of two tests that are run in that step is failing for some reason.

**Review by tabishop — APPROVED** [review]
LGTM

**Review by csandersdev — APPROVED** [review]
LGTM

**Review by msargentibm — APPROVED** [review]

**Pull request merged**
